server:
  port: 80  #Consul服务端口号

spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul: #consul注册中心相关配置
      host: localhost
      port: 8500
      discovery:
        hostname: coreqi
        service-name: ${spring.application.name}