server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:  #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit:  #表示定义的名称，用于与binding整合
          type: rabbit  #消息组件类型
          environment:  #设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 192.168.57.128
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #这个名字是一个通道的名称 消息的生产者发送
          destination: studyExchange  #表示要使用的Exchange名称定义 约定好的目的的通道名称
          content-type: application/json  #设置消息类型，本次为json，文本则设置为“text/plain”
          binder: defaultRabbit #设置要绑定的消息服务的具体设置

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka （单机版Eureka）
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #向Eureka集群分别注册
  instance:
    instance-id: receive-8802.com  #在Eureka注册中心显示的主机名称
    prefer-ip-address: true #是否在Eureka注册中心显示ip地址
    lease-renewal-interval-in-seconds: 2  #设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 #Eureka Server在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务